routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;


// Binds for route
Route::pattern('id', '\d+');

//Route::domain(env('APP_URL'))->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Auth::routes();

    Route::group(['middleware' => 'auth'], function () {
        Route::get('/', 'CPController@index')->name('cp');

        Route::get('/instruction', 'CPController@instruction')->name('instruction');
        Route::get('profile',           ['as' => 'profile',         'uses' => 'Auth\LoginController@profile']);
        Route::post('profile',          ['as' => 'profile_update',  'uses' => 'Auth\LoginController@profileUpdate']);

        // Пользователи
        MyRoute::resourcePermission('users', 'CP\UserController', [
            'show' => function () {
                Route::any('users/datatable', ['as' => 'users.datatables.data', 'uses' => 'CP\UserController@anyData']);
            }
        ]);

        // Менеджер файлов
        MyRoute::checkPermission('filemanager', [
            'show' => function () {
                Route::get('/filemanager', ['as' => 'filemanager.index', 'uses' => 'CPController@filemanager']);
            }
        ]);

        // Роли/Разрешения
        Route::group(['prefix' => 'rbac', 'as' => 'rbac.'], function () {
            MyRoute::resourcePermission('rbac.roles', 'CP\RBAC\RoleController', [
                'show' => function () {
                    Route::any('roles/datatable', ['as' => 'roles.datatables.data', 'uses' => 'CP\RBAC\RoleController@anyData']);
                }
            ]);

            MyRoute::resourcePermission('rbac.permissions', 'CP\RBAC\PermissionController', [
                'show' => function () {
                    Route::any('permissions/datatable', ['as' => 'permissions.datatables.data', 'uses' => 'CP\RBAC\PermissionController@anyData']);
                }
            ]);
        });

        // Инспекторы
        MyRoute::resourcePermission('inspectors', 'InspectorController', [
            'show' => function () {
                Route::any('inspectors/datatable', ['as' => 'inspectors.datatables.data', 'uses' => 'InspectorController@anyData']);
                Route::any('inspectors/excel', ['as' => 'inspectors.excel', 'uses' => 'InspectorController@getExcel']);
            },
            'edit' => function() {
                Route::post('inspectors/{inspector}/delete_file', ['as' => 'inspectors.delete_file', 'uses' => 'InspectorController@deleteFile']);
                Route::get('inspectors/{inspector}/readonly', ['as' => 'inspectors.readonly', 'uses' => 'InspectorController@readonly']);
            }
        ]);

        // Реестр Материалов
        MyRoute::resourcePermission('materials', 'MaterialController', [
            'show' => function () {
                Route::any('materials/datatable', ['as' => 'materials.datatables.data', 'uses' => 'MaterialController@anyData']);
                Route::any('materials/excel', ['as' => 'materials.excel', 'uses' => 'MaterialController@getExcel']);
            },
            'edit' => function() {
                Route::post('materials/{material}/delete_file', ['as' => 'materials.delete_file', 'uses' => 'MaterialController@deleteFile']);
                Route::get('materials/{material}/readonly', ['as' => 'materials.readonly', 'uses' => 'MaterialController@readonly']);
            }
        ]);

        // Реестр Мероприятий
        MyRoute::resourcePermission('reg_events', 'RegEventController', [
            'show' => function () {
                Route::any('reg_events/datatable', ['as' => 'reg_events.datatables.data', 'uses' => 'RegEventController@anyData']);
                Route::any('reg_events/excel', ['as' => 'reg_events.excel', 'uses' => 'RegEventController@getExcel']);
            },
            'edit' => function() {
                Route::post('reg_events/{reg_event}/delete_file', ['as' => 'reg_events.delete_file', 'uses' => 'RegEventController@deleteFile']);
                Route::get('reg_events/{reg_event}/readonly', ['as' => 'reg_events.readonly', 'uses' => 'RegEventController@readonly']);
            }
        ]);

        // Доступные роуты пользователя
        Route::group(['middleware' => 'role:admin'], function () {
            Route::any('inspectors/{inspector}/audit', ['as' => 'inspectors.audit', 'uses' => 'InspectorController@audit']);
            Route::any('materials/{material}/audit', ['as' => 'materials.audit', 'uses' => 'MaterialController@audit']);
            Route::any('reg_events/{reg_event}/audit', ['as' => 'reg_events.audit', 'uses' => 'RegEventController@audit']);

            Route::get('routes', function () {
                $routeCollection = Route::getRoutes();

                echo "<table style='width:100%'>";
                echo "<tr>";
                echo "<td width='10%'><h4>Name (as, path)</h4></td>";
                echo "<td width='50%'><h4>Corresponding Action</h4></td>";
                echo "<td width='10%'><h4>Methods</h4></td>";
                echo "<td width='30%'><h4>Uri (prefix, path)</h4></td>";
                echo "</tr>";
                foreach ($routeCollection as $value) {
                    echo "<tr>";
                    echo "<td>" . $value->getName() . "</td>";
                    echo "<td>" . $value->getActionName() . "</td>";
                    echo "<td>" . implode(', ', $value->methods()) . "</td>";
                    echo "<td>" . $value->uri() . "</td>";
                    echo "</tr>";
                }
                echo "</table>";
            });
        });
    });

    // Не правильное api не так надо делать
//    Route::group(['middleware' => 'api.token.verify', 'prefix' => 'api'], function () {
//        // Сохранение заявок
//        Route::post('orders/{usermib}', 'CP\Orders\JsonController@saveOrder');
//    });

//});

app/Models/RBAC/Permission.php
<?php

namespace App\Models\RBAC;

use Laratrust\LaratrustPermission;
use Spatie\Activitylog\Traits\LogsActivity;

class Permission extends LaratrustPermission {
    use LogsActivity;

    // Игнорирует логирование изменений полей
    protected static $ignoreChangedAttributes = ['created_at', 'updated_at'];

    // какие поля логируем
    protected static $logAttributes = ['*'];

    // Логируем только те поля, которые действительно изменились
    protected static $logOnlyDirty = true;

    protected $fillable = [
        'name', 'display_name', 'description',
    ];

    public function getGroupPermissions()
    {
        $groups = trans('permission.groups');
        $all = $this->orderBy('id', 'ASC')->get();
        foreach($all as $one) {
            $hasGroup = false;
            foreach($groups as $name => &$onegroup) {
                if (!isset($onegroup['lists'])) {
                    $onegroup = [
                        'name'  => $onegroup,
                        'lists' => []
                    ];
                }
                if (strpos($one->name, $name) === 0) {
                    array_push($onegroup['lists'], $one);
                    $hasGroup = true;
                    break;
                }
            }

            if (!$hasGroup) {
                array_push($groups['other']['lists'], $one);
            }
        }
        //echo'<pre>';print_r($groups);die;
        return $groups;
    }

}

app/Models/RBAC/Role.php
<?php

namespace App\Models\RBAC;

use Laratrust\LaratrustRole;
use Spatie\Activitylog\Traits\LogsActivity;

class Role extends LaratrustRole {
    use LogsActivity;

    // Игнорирует логирование изменений полей
    protected static $ignoreChangedAttributes = ['created_at', 'updated_at'];

    // какие поля логируем
    protected static $logAttributes = ['*'];

    // Логируем только те поля, которые действительно изменились
    protected static $logOnlyDirty = true;

    // на какое действие включаем логирование
    protected static $recordEvents = ['created', 'updated', 'deleted'];

    protected $fillable = [
        'name', 'display_name', 'description'
    ];
}

app/Http/Controllers/CP/RBAC/PermissionController.php
<?php

namespace App\Http\Controllers\CP\RBAC;

use App\Http\Requests\RBAC\Permission\PermissionCreateRequest;
use App\Http\Requests\RBAC\Permission\PermissionUpdateRequest;
use App\Models\RBAC\Permission;
use App\Http\Controllers\Controller;
use Yajra\Datatables\Datatables;

class PermissionController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('cp.rbac.permissions.index');
    }


    /**
     * @return mixed
     * @throws \Exception
     */
    public function anyData()
    {
        return Datatables::of(Permission::query())
            ->addColumn('action', function ($permission) {
                return view('cp.parts.actions', ['controller'=>'rbac.permissions', 'object'=>$permission, 'action'=>'table']);
            })
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cp.rbac.permissions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param PermissionCreateRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(PermissionCreateRequest $request)
    {
        $permission = Permission::create($request->all());
        $permission->roles()->sync($request->input('roles'));

        return redirect()->action('CP\RBAC\PermissionController@show', $permission)->with('success', __('messages.create'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\RBAC\Permission $permission
     * @return \Illuminate\Http\Response
     */
    public function show(Permission $permission)
    {
        return view('cp.rbac.permissions.show', compact('permission'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\RBAC\Permission $permission
     * @return \Illuminate\Http\Response
     */
    public function edit(Permission $permission)
    {
        return view('cp.rbac.permissions.edit', compact('permission'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param PermissionUpdateRequest $request
     * @param  \App\Models\RBAC\Permission $permission
     * @return \Illuminate\Http\Response
     */
    public function update(PermissionUpdateRequest $request, Permission $permission)
    {
        $permission->update($request->all());
        $permission->roles()->sync($request->input('roles'));

        return redirect()->action('CP\RBAC\PermissionController@show', $permission)->with('success', __('messages.update'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\RBAC\Permission $permission
     * @return \Illuminate\Http\Response
     */
    public function destroy(Permission $permission)
    {
        $permission->delete();

        return redirect()->action('CP\RBAC\PermissionController@index')->with('success', __('messages.delete'));
    }
}

app/Http/Controllers/CP/RBAC/RoleController.php
<?php

namespace App\Http\Controllers\CP\RBAC;

use App\Http\Requests\RBAC\Role\RoleCreateRequest;
use App\Http\Requests\RBAC\Role\RoleUpdateRequest;
use App\Models\RBAC\Role;
use App\Http\Controllers\Controller;
use Yajra\Datatables\Datatables;

class RoleController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('cp.rbac.roles.index');
    }

    /**
     * @return mixed
     * @throws \Exception
     */
    public function anyData()
    {
        return Datatables::of(Role::query())
            ->addColumn('action', function ($permission) {
                return view('cp.parts.actions', ['controller'=>'rbac.roles', 'object'=>$permission, 'action'=>'table']);
            })
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cp.rbac.roles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param RoleCreateRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(RoleCreateRequest $request)
    {
        $role = Role::create($request->all());
        $role->permissions()->sync($request->input('permissions'));

        return redirect()->action('CP\RBAC\RoleController@show', $role)->with('success', __('messages.create'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\RBAC\Role $role
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        return view('cp.rbac.roles.show', compact('role'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\RBAC\Role $role
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        return view('cp.rbac.roles.edit', compact('role'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param RoleUpdateRequest $request
     * @param  \App\Models\RBAC\Role $role
     * @return \Illuminate\Http\Response
     */
    public function update(RoleUpdateRequest $request, Role $role)
    {
        $role->update($request->all());
        $role->permissions()->sync($request->input('permissions'));

        return redirect()->action('CP\RBAC\RoleController@show', $role)->with('success', __('messages.update'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\RBAC\Role $role
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        $role->delete();

        return redirect()->action('CP\RBAC\RoleController@index')->with('success', __('messages.delete'));
    }
}

resources/views/cp/rbac/roles/create.blade.php
@extends('cp.layouts.default')

@section('page-title', __('cp.create').": ".__('cp.role'))

@section('page-header')

    <h1>@lang('cp.create')</h1>

@endsection

@section('content')

    <div class="panel panel-default">

        <div class="panel-body">

            @include('cp.parts.actions', ['controller'=>'rbac.roles'])

        </div>

    </div>

    <form action="{{ action('CP\RBAC\RoleController@store') }}" method="POST">

        {{ csrf_field() }}

        <div class="panel panel-default">

            <div class="panel-body">

                <div class="form-group">
                    <label for="name">@lang('cp.name')</label>
                    <input type="text" id="name" name="name" placeholder="@lang('cp.name')" value="{{ old('name') }}"
                           class="form-control">
                </div>

                <div class="form-group">
                    <label for="display_name">@lang('cp.display_name')</label>
                    <input type="text" id="display_name" name="display_name" placeholder="@lang('cp.display_name')"
                           value="{{ old('display_name') }}" class="form-control">
                </div>

                <div class="form-group">
                    <label for="description">@lang('cp.description')</label>
                    <textarea id="description" name="description" placeholder="@lang('cp.description')"
                              class="form-control">{{ old('description') }}</textarea>
                </div>

                <div class="form-group pull-right">
                    <button class="btn btn-primary">@lang('cp.create')</button>
                </div>

            </div>

        </div>

        <div class="panel panel-default">

            <div class="panel-heading">
                @lang('cp.permissions')
                <label class="pull-right">
                    <input type="checkbox" class="check_all" v-name="permissions"> Выбрать все:
                </label>
            </div>

            <div class="panel-body">

                <div class="form-group">
                    @foreach(app(\App\Models\RBAC\Permission::class)->getGroupPermissions() as $group)
                        @continue(!isset($group['lists']))
                        <ul class="list-style-none">
                            <li>
                                <h4>{{  $group['name'] }}</h4>
                                <ul class="list-style-none">
                                    @foreach($group['lists'] as $permission)
                                        <li>
                                            <label><input type="checkbox" name="permissions[]" value="{{ $permission->id }}"
                                                          title="{{ $permission->display_name }}"> {{ $permission->display_name }}
                                            </label>
                                        </li>
                                    @endforeach
                                </ul>
                            </li>
                        </ul>
                    @endforeach
                </div>

                <div class="form-group pull-right">
                    <button class="btn btn-primary">@lang('cp.create')</button>
                </div>

            </div>

        </div>

    </form>

@endsection

resources/views/cp/rbac/roles/edit.blade.php
@extends('cp.layouts.default')

@section('page-title', __('cp.edit').": ".__('cp.role')." $role->name")

@section('page-header')

    <h1>@lang('cp.edit')
        <small>{!! $role->name !!}</small>
    </h1>

@endsection

@section('content')

    <div class="panel panel-default">

        <div class="panel-body">

            @include('cp.parts.actions', ['controller'=>'rbac.roles', 'object'=>$role])

        </div>

    </div>

    <form action="{{ action('CP\RBAC\RoleController@update', $role) }}" method="POST">

        <input type="hidden" name="_method" value="PUT">

        {{ csrf_field() }}

        <div class="panel panel-default">

            <div class="panel-body">

                <div class="form-group">
                    <label for="name">@lang('cp.name')</label>
                    <input type="text" id="name" name="name" value="{{ $role->name }}" placeholder="@lang('cp.name')"
                           class="form-control">
                </div>

                <div class="form-group">
                    <label for="display_name">@lang('cp.display_name')</label>
                    <input type="text" id="display_name" name="display_name" value="{{ $role->display_name }}"
                           placeholder="@lang('cp.display_name')"
                           class="form-control">
                </div>

                <div class="form-group">
                    <label for="description">@lang('cp.description')</label>
                    <textarea id="description" name="description" placeholder="@lang('cp.description')"
                              class="form-control">{{ $role->description }}</textarea>
                </div>

                <div class="form-group pull-right">
                    <button class="btn btn-primary">@lang('cp.save')</button>
                </div>


            </div>

        </div>


        <div class="panel panel-default">

            <div class="panel-heading">
                @lang('cp.permissions')
                <label class="pull-right">
                    <input type="checkbox" class="check_all" v-name="permissions"> Выбрать все:
                </label>
            </div>

            <div class="panel-body">

                <div class="form-group">
                    @foreach(app(\App\Models\RBAC\Permission::class)->getGroupPermissions() as $group)
                        @continue(!isset($group['lists']))
                        <ul class="list-style-none">
                            <li>
                                <h4>{{  $group['name'] }}</h4>
                                <ul class="list-style-none">
                                    @foreach($group['lists'] as $permission)
                                        @php
                                            $checked = $role->hasPermission($permission->name) ? ' checked': '';
                                        @endphp
                                        <li>
                                            <label><input type="checkbox" name="permissions[]" value="{{ $permission->id }}"
                                                          title="{{ $permission->display_name }}"{{ $checked }}> {{ $permission->display_name }}
                                            </label>
                                        </li>
                                    @endforeach
                                </ul>
                            </li>
                        </ul>
                    @endforeach
                </div>

                <div class="form-group pull-right">
                    <button class="btn btn-primary">@lang('cp.save')</button>
                </div>

            </div>

        </div>

    </form>

@endsection

resources/views/cp/rbac/roles/index.blade.php
@extends('cp.layouts.default')

@section('page-title', __('cp.roles'))

@section('page-header')

    <h1>@lang('cp.roles')</h1>

@endsection

@section('content')

    <div class="panel panel-default">

        <div class="panel-body">

            @include('cp.parts.actions', ['controller'=>'rbac.roles'])

        </div>

    </div>

    <div class="panel panel-default">

        <div class="panel-body">

            @include('cp.rbac.roles.table')

        </div>

    </div>

@endsection

resources/views/cp/rbac/roles/show.blade.php
@extends('cp.layouts.default')

@section('page-title', __('cp.role')." $role->name")

@section('page-header')

    <h1>@lang('cp.role')
        <small>{{ $role->name }}</small>
    </h1>

@endsection

@section('content')

    <div class="panel panel-info">

        <div class="panel-body">

            @include('cp.parts.actions', ['controller'=>'rbac.roles', 'object'=>$role])

        </div>

    </div>

    <div class="panel panel-default">

        <div class="panel-body">

            <table class="table table-responsive table-bordered table-striped">
                <tbody>
                <tr>
                    <td>@lang('cp.id')</td>
                    <td>{{ $role->id }}</td>
                </tr>
                <tr>
                    <td>@lang('cp.name')</td>
                    <td>{{ $role->name }}</td>
                </tr>
                <tr>
                    <td>@lang('cp.display_name')</td>
                    <td>{{ $role->display_name }}</td>
                </tr>
                <tr>
                    <td>@lang('cp.description')</td>
                    <td>{{ $role->description }}</td>
                </tr>
                <tr>
                    <td>@lang('cp.created_at')</td>
                    <td>{{ $role->created_at }}</td>
                </tr>
                <tr>
                    <td>@lang('cp.updated_at')</td>
                    <td>{{ $role->updated_at }}</td>
                </tr>
                </tbody>
            </table>

        </div>

    </div>

    <div class="panel panel-default">

        <div class="panel-heading">
            @lang('cp.permissions')
        </div>

        <div class="panel-body">

            <ul>
                @foreach($role->permissions as $permission)
                    <li>
                        <a href="{{ action('CP\RBAC\PermissionController@show', $permission) }}">{{ $permission->display_name }}</a>
                    </li>
                @endforeach
            </ul>
        </div>

    </div>

@endsection

resources/views/cp/rbac/roles/table.blade.php
<table id="table-roles" class="table table-responsive table-bordered table-striped">
    <thead>
    <tr>
        <th>@lang('cp.id')</th>
        <th>@lang('cp.name')</th>
        <th>@lang('cp.display_name')</th>
        <th>@lang('cp.description')</th>
        <th>@lang('cp.table_actions')</th>
    </tr>
    </thead>
</table>
@section('scripts')
<script>
$(function() {
    $('#table-roles').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route('rbac.roles.datatables.data') !!}',
        language: {
            "url": "{{ asset('vendor/datatables/js/ru.lang') }}"
        },
        columns: [
            { data: 'id', name: 'id' },
            { data: 'name', name: 'name' },
            { data: 'display_name', name: 'display_name' },
            { data: 'description', name: 'description' },
            { data: 'action', name: 'action', orderable: false, searchable: false}
        ]
    });
});
</script>
@endsection